version: "3.8"

services:
  app:
    #build:
    #  context: docker
    image: my-bartender-service:latest-local
    ports:
      - "8080:8080" # http://localhost:8080/health
    links:
      - db:db
      - localstack:localstack
    environment:
      - aws.localstack.enabled=true
      - aws.localstack.sqs.endpointOverride=http://localstack:4566
      - aws.localstack.sns.endpointOverride=http://localstack:4566
    depends_on:
      - db
      - localstack
  db:
    image: postgres:14
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  localstack:
    container_name: localstack_main
    image: localstack/localstack:1.4.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
