version: "3.8"

services:
  app:
    build:
      context: docker
    ports:
      - "8080:8080" # http://localhost:8080/health
    links:
      - db:db
  db:
    image: postgres:14
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
